// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/kv-server.proto

package kvstore_methods

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Value struct {
	Values               []byte   `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_1477b0e33c60977b, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetValues() []byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type Values struct {
	Values               []*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Cursor               int32    `protobuf:"varint,2,opt,name=Cursor,proto3" json:"Cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Values) Reset()         { *m = Values{} }
func (m *Values) String() string { return proto.CompactTextString(m) }
func (*Values) ProtoMessage()    {}
func (*Values) Descriptor() ([]byte, []int) {
	return fileDescriptor_1477b0e33c60977b, []int{1}
}

func (m *Values) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values.Unmarshal(m, b)
}
func (m *Values) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values.Marshal(b, m, deterministic)
}
func (m *Values) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values.Merge(m, src)
}
func (m *Values) XXX_Size() int {
	return xxx_messageInfo_Values.Size(m)
}
func (m *Values) XXX_DiscardUnknown() {
	xxx_messageInfo_Values.DiscardUnknown(m)
}

var xxx_messageInfo_Values proto.InternalMessageInfo

func (m *Values) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Values) GetCursor() int32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

type Key struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_1477b0e33c60977b, []int{2}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type KVPair struct {
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *Value   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVPair) Reset()         { *m = KVPair{} }
func (m *KVPair) String() string { return proto.CompactTextString(m) }
func (*KVPair) ProtoMessage()    {}
func (*KVPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_1477b0e33c60977b, []int{3}
}

func (m *KVPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVPair.Unmarshal(m, b)
}
func (m *KVPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVPair.Marshal(b, m, deterministic)
}
func (m *KVPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVPair.Merge(m, src)
}
func (m *KVPair) XXX_Size() int {
	return xxx_messageInfo_KVPair.Size(m)
}
func (m *KVPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KVPair.DiscardUnknown(m)
}

var xxx_messageInfo_KVPair proto.InternalMessageInfo

func (m *KVPair) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KVPair) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

// whether the operation is ok
type OperationOK struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationOK) Reset()         { *m = OperationOK{} }
func (m *OperationOK) String() string { return proto.CompactTextString(m) }
func (*OperationOK) ProtoMessage()    {}
func (*OperationOK) Descriptor() ([]byte, []int) {
	return fileDescriptor_1477b0e33c60977b, []int{4}
}

func (m *OperationOK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationOK.Unmarshal(m, b)
}
func (m *OperationOK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationOK.Marshal(b, m, deterministic)
}
func (m *OperationOK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationOK.Merge(m, src)
}
func (m *OperationOK) XXX_Size() int {
	return xxx_messageInfo_OperationOK.Size(m)
}
func (m *OperationOK) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationOK.DiscardUnknown(m)
}

var xxx_messageInfo_OperationOK proto.InternalMessageInfo

func (m *OperationOK) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

// the args of scan
type ScanArgs struct {
	Cursor               int32    `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Match                *Key     `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanArgs) Reset()         { *m = ScanArgs{} }
func (m *ScanArgs) String() string { return proto.CompactTextString(m) }
func (*ScanArgs) ProtoMessage()    {}
func (*ScanArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_1477b0e33c60977b, []int{5}
}

func (m *ScanArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanArgs.Unmarshal(m, b)
}
func (m *ScanArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanArgs.Marshal(b, m, deterministic)
}
func (m *ScanArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanArgs.Merge(m, src)
}
func (m *ScanArgs) XXX_Size() int {
	return xxx_messageInfo_ScanArgs.Size(m)
}
func (m *ScanArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ScanArgs proto.InternalMessageInfo

func (m *ScanArgs) GetCursor() int32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *ScanArgs) GetMatch() *Key {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *ScanArgs) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*Value)(nil), "kvstore.methods.Value")
	proto.RegisterType((*Values)(nil), "kvstore.methods.Values")
	proto.RegisterType((*Key)(nil), "kvstore.methods.Key")
	proto.RegisterType((*KVPair)(nil), "kvstore.methods.KVPair")
	proto.RegisterType((*OperationOK)(nil), "kvstore.methods.OperationOK")
	proto.RegisterType((*ScanArgs)(nil), "kvstore.methods.ScanArgs")
}

func init() { proto.RegisterFile("proto/kv-server.proto", fileDescriptor_1477b0e33c60977b) }

var fileDescriptor_1477b0e33c60977b = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xdf, 0x4b, 0xfa, 0x50,
	0x14, 0x77, 0xdb, 0x77, 0xc3, 0xef, 0x31, 0x2a, 0x0e, 0xa6, 0x26, 0x45, 0x72, 0x1f, 0x42, 0xa2,
	0x16, 0x18, 0xbd, 0x45, 0x10, 0x05, 0x3d, 0xec, 0x41, 0x99, 0xe0, 0x63, 0xb0, 0xe6, 0x21, 0x65,
	0xea, 0x95, 0x7b, 0xaf, 0x03, 0x1f, 0xfb, 0xcf, 0x63, 0x67, 0x13, 0xa4, 0x39, 0x7a, 0xda, 0xfd,
	0x70, 0x3e, 0xbf, 0xce, 0x61, 0x70, 0xb6, 0x56, 0xd2, 0xc8, 0xfb, 0x24, 0xbd, 0xd3, 0xa4, 0x52,
	0x52, 0x3e, 0x63, 0x3c, 0x49, 0x52, 0x6d, 0xa4, 0x22, 0x7f, 0x49, 0x66, 0x26, 0xa7, 0x5a, 0x5c,
	0x81, 0x3b, 0x89, 0x16, 0x1b, 0xc2, 0x16, 0x78, 0x69, 0xf6, 0xd0, 0x1d, 0xab, 0x67, 0xf5, 0x8f,
	0xc2, 0x02, 0x89, 0x11, 0x78, 0x4c, 0xd0, 0xe8, 0xef, 0x31, 0x9c, 0x7e, 0x63, 0xd0, 0xf2, 0x7f,
	0x99, 0xf9, 0x4c, 0xdc, 0x29, 0x33, 0xc7, 0xd7, 0x8d, 0xd2, 0x52, 0x75, 0xec, 0x9e, 0xd5, 0x77,
	0xc3, 0x02, 0x89, 0x36, 0x38, 0x01, 0x6d, 0xf1, 0x94, 0x3f, 0x9c, 0xf6, 0x3f, 0xcc, 0x9e, 0xe2,
	0x03, 0xbc, 0x60, 0x32, 0x8a, 0xe6, 0x0a, 0xaf, 0xc1, 0x49, 0x8a, 0x59, 0x63, 0xd0, 0x2c, 0xe5,
	0x04, 0xb4, 0x0d, 0x33, 0x02, 0xde, 0x82, 0xcb, 0x61, 0x9c, 0x50, 0xdd, 0x28, 0x27, 0x89, 0x4b,
	0x68, 0x0c, 0xd7, 0xa4, 0x22, 0x33, 0x97, 0xab, 0x61, 0x80, 0xc7, 0x60, 0xcb, 0x84, 0x33, 0xea,
	0xa1, 0x2d, 0x13, 0x31, 0x85, 0xfa, 0x38, 0x8e, 0x56, 0x2f, 0xea, 0x8b, 0xbb, 0xc7, 0x79, 0x77,
	0x2b, 0xef, 0x9e, 0x23, 0xbc, 0x01, 0x77, 0x19, 0x99, 0x78, 0x56, 0x04, 0x1e, 0xae, 0x96, 0x53,
	0xb0, 0x09, 0x6e, 0x2c, 0x37, 0x2b, 0xd3, 0x71, 0xd8, 0x22, 0x07, 0x83, 0x6f, 0x1b, 0x20, 0x98,
	0x8c, 0x49, 0xa5, 0xf3, 0x98, 0x14, 0x3e, 0x82, 0xf3, 0x4e, 0x06, 0x0f, 0x1a, 0x75, 0x2b, 0xf6,
	0x11, 0x35, 0x7c, 0x06, 0x67, 0x4c, 0x06, 0xdb, 0x65, 0x19, 0x1f, 0xb0, 0x7b, 0x51, 0x1a, 0xec,
	0x6d, 0xce, 0x7a, 0xef, 0x8d, 0x16, 0x64, 0xa8, 0x22, 0xf9, 0x2f, 0xfd, 0x13, 0xfc, 0xcb, 0x6e,
	0x85, 0xe7, 0x25, 0xde, 0xee, 0x84, 0xdd, 0xf6, 0xe1, 0xf2, 0x5a, 0xd4, 0x3e, 0x3d, 0xfe, 0x19,
	0x1f, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x45, 0xc8, 0x7b, 0xa5, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KVServicerClient is the client API for KVServicer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KVServicerClient interface {
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error)
	Set(ctx context.Context, in *KVPair, opts ...grpc.CallOption) (*OperationOK, error)
	Delete(ctx context.Context, in *Key, opts ...grpc.CallOption) (*OperationOK, error)
	Scan(ctx context.Context, in *ScanArgs, opts ...grpc.CallOption) (*Values, error)
}

type kVServicerClient struct {
	cc *grpc.ClientConn
}

func NewKVServicerClient(cc *grpc.ClientConn) KVServicerClient {
	return &kVServicerClient{cc}
}

func (c *kVServicerClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/kvstore.methods.KVServicer/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVServicerClient) Set(ctx context.Context, in *KVPair, opts ...grpc.CallOption) (*OperationOK, error) {
	out := new(OperationOK)
	err := c.cc.Invoke(ctx, "/kvstore.methods.KVServicer/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVServicerClient) Delete(ctx context.Context, in *Key, opts ...grpc.CallOption) (*OperationOK, error) {
	out := new(OperationOK)
	err := c.cc.Invoke(ctx, "/kvstore.methods.KVServicer/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVServicerClient) Scan(ctx context.Context, in *ScanArgs, opts ...grpc.CallOption) (*Values, error) {
	out := new(Values)
	err := c.cc.Invoke(ctx, "/kvstore.methods.KVServicer/Scan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVServicerServer is the server API for KVServicer service.
type KVServicerServer interface {
	Get(context.Context, *Key) (*Value, error)
	Set(context.Context, *KVPair) (*OperationOK, error)
	Delete(context.Context, *Key) (*OperationOK, error)
	Scan(context.Context, *ScanArgs) (*Values, error)
}

func RegisterKVServicerServer(s *grpc.Server, srv KVServicerServer) {
	s.RegisterService(&_KVServicer_serviceDesc, srv)
}

func _KVServicer_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServicerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvstore.methods.KVServicer/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServicerServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVServicer_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVPair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServicerServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvstore.methods.KVServicer/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServicerServer).Set(ctx, req.(*KVPair))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVServicer_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServicerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvstore.methods.KVServicer/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServicerServer).Delete(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVServicer_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServicerServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvstore.methods.KVServicer/Scan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServicerServer).Scan(ctx, req.(*ScanArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _KVServicer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kvstore.methods.KVServicer",
	HandlerType: (*KVServicerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KVServicer_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _KVServicer_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KVServicer_Delete_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _KVServicer_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kv-server.proto",
}
